import type { LlmProvider, ProviderRequest, ProviderResponse } from "./llm-provider.js";
import { estimateTokenUsage } from "../budget/token-estimator.js";

export class MockProvider implements LlmProvider {
  readonly name = "mock";

  async complete(request: ProviderRequest): Promise<ProviderResponse> {
    const estimate = estimateTokenUsage({
      inputText: request.prompt,
      expectedOutputTokens: 160
    });

    return {
      content: [
        `# ${request.agent} output`,
        "",
        `Tier: ${request.tier}`,
        "",
        "This artifact was generated by the scaffolded mock provider.",
        "",
        "## Notes",
        "",
        "- Replace this provider with a real LLM integration.",
        "- Preserve deterministic artifact layout."
      ].join("\n"),
      promptTokens: estimate.estimatedInputTokens,
      completionTokens: estimate.estimatedOutputTokens,
      estimatedCostUsd: estimate.estimatedCostUsd
    };
  }
}
