import type { LlmProvider, ProviderRequest, ProviderResponse } from "./llm-provider.js";

export class MockProvider implements LlmProvider {
  readonly name = "mock";

  async complete(request: ProviderRequest): Promise<ProviderResponse> {
    const promptTokens = Math.max(32, Math.ceil(request.prompt.length / 4));
    const completionTokens = 160;

    return {
      content: [
        `# ${request.agent} output`,
        "",
        `Tier: ${request.tier}`,
        "",
        "This artifact was generated by the scaffolded mock provider.",
        "",
        "## Notes",
        "",
        "- Replace this provider with a real LLM integration.",
        "- Preserve deterministic artifact layout."
      ].join("\n"),
      promptTokens,
      completionTokens,
      estimatedCostUsd: Number(((promptTokens + completionTokens) * 0.000002).toFixed(4))
    };
  }
}
